server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
     routes:
      - id: employee-microservice
        uri: lb://employee-microservice
        predicates:
         - Path=/empl/**,/leav/**,/pays/**,/sala/**,/timeshe/**
      - id: admin-microservice
        uri: lb://admin-microservice
        predicates:
         - Path=/admine/**,/adminl/**,/adminp/**,/admins/**,/admint/**
      - id: google
        uri: http://www.google.com
        predicates:
         - Path=/redirect/**

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:  ${EUREKA_SERVER:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"